#!/bin/bash
accountid=$(aws sts get-caller-identity --query "Account" --output text)

aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $accountid.dkr.ecr.eu-central-1.amazonaws.com
